### ISSUE TITLE
Add question which allows file uploads

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#1]
Polar Access Fund requires two compulsary and one optional file upload. 

- Create a question with an answer of a different type, which would be file upload. 
- Ensure the file upload can compulsary or optional.

**Comment by jen-thomas** [comment]
Consider if the file type should be specified?

**Comment by cpina** [comment]
I'll close this one and let's evaluate if we need a file type or maximum file size (probably after stage 1)
