### ISSUE TITLE
ability to change labels / help_text on the "Proposal" section of the create proposal

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#109]
Check that the text is correct and can be adapted to each call individually, or at least not cause confusion by the details of what is asked. 

This could be that we keep the main text and allow the help text to be changed with each call, or allow more flexibility of changing the text or the fields for a call. 

Alternatively have different questions for the different types of call and allow the user to add a question or not.

**Comment by cpina** [comment]
After discussing: the labels / help_text of the "Proposal" section should be editable per call.

**Comment by jen-thomas** [comment]
For the polar access fund: perhaps just change the texts that are used, then we can work on a fuller solution. 

The following texts should be changed: 
- Title -> proposed field trip
- Select all options describing the geographical focus of this proposal -> select all options describing where the field trip would take place
- More precise location of where proposal would take place (not coordinates) -> more precise region of where the field trip would take place (not coordinates)
- Keywords that describe the proposal -> Keywords that describe the proposed field work
- Approximate date on which the proposed project is expected to start -> Approximate date on which the proposed field trip is expected to start
- Approximate date on which the proposed project is expected to end -> Approximate date on which the proposed field trip is expected to end
- Part 2: Project Description -> Part 2: Proposed field trip

**Comment by jen-thomas** [comment]
Texts changed as: https://github.com/Swiss-Polar-Institute/project-application/issues/140
