### ISSUE TITLE
review - login for reviewers to see proposals for a specific call?

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#110]
Should there be the possibility for a reviewer to login to the application and see the proposals for a specific call (limited to a specific call)?

This would avoid having to download files and share them, which would be better for privacy. 
(following discussion with Laurence and Basil, November 2019)

**Comment by jen-thomas** [comment]
See how the current implementation goes: https://github.com/Swiss-Polar-Institute/project-application/issues/112

If this is ok, then we can implement access to only certain subsets of proposals

**Comment by cpina** [comment]
This is done - I'll open a new ticket for reviewer management
