### ISSUE TITLE
add organisation to proposal partner form

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#114]
Should organisation be part of the proposal partner form? The group lab is there currently, but not the details of the organisaiton.

**Comment by jen-thomas** [comment]
It should also be added to the get or create list of fields around line 103

**Comment by cpina** [comment]
Done: https://github.com/Swiss-Polar-Institute/project-application/commit/3f053ec52956b7075a6355d8c121761469bfbf85 (partially here and partially in an earlier commit)
