### ISSUE TITLE
do not allow submission if files cannot be attached to proposal

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#124]
if a file cannot be attached, currently the proposal is submitted, but an error does occur warning the user about the file not being attached. 

it might make more sense if the proposal is not submitted and only saved as a draft.
![Screenshot from 2019-11-27 17-53-07](https://user-images.githubusercontent.com/14336311/69747786-e96b7680-113e-11ea-9869-cf514e74e76e.png)

**Comment by jen-thomas** [comment]
Difficult to do this whilst the application is being completed, although as the question field will be mandatory then they user will be required to add something. 

We are concerned by a file not properly being saved by the object storage i.e. the storage is not available for some reason. 

When a user presses submit, if the file has not been saved correctly, then:
- change the status of the proposal back to draft (this is important otherwise they will not be able to edit any longer)
- ensure there is a message saying that the file has not been attached (this already appears I think) and they should retry
- ensure there is a message stating that the proposal has not been submitted

**Comment by cpina** [comment]
Just to add: at the moment (pending deployment to production) if a file is not uploaded we will get an alert.

**Comment by jen-thomas** [comment]
could be access key problems, network problems etc with S3 that avoid the file being uploaded
