### ISSUE TITLE
create possibility to add multiple files to a question answer

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#125]
In the technogrants application form (and possibly others) there is the need to upload the cv of an applicant (this can already be done by creating a call question with a file type as an answer). 

Another question asking about the partners though asks for CVs of all main partners - these would be multiple file attachments to another question. 
example from Technogrants: CV of the PI and main partners should be included as appendix

This is not required for the polar access fund but will be needed for the other application forms.

**Comment by cpina** [comment]
Moving it to stage n - probably not trivial, not scoped for stage 2

**Comment by cpina** [comment]
This was also commented by Danièle during the run "Exploratory cooking fund" test.

**Comment by cpina** [comment]
In the Exploratory Grants 2020 one applicant couldn't merge the files in time.
