### ISSUE TITLE
funding organisation not a valid choice

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#126]
![Screenshot from 2019-11-29 10-29-22](https://user-images.githubusercontent.com/14336311/69862807-319bad80-1293-11ea-8dbf-502bebc0ab34.png)

Organisations have now changed to organisation names. When creating a proposal (logged out user), the funding organisation is not now valid. See screenshot.

**Comment by cpina** [comment]
This was fixed on Friday
