### ISSUE TITLE
change proposal partner text, assume applicant part of proposal

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#127]
Currently we assume that an applicant may or may not be part of the proposed project. This causes confusion with having to add the applicants CV (whcih wouldn't be needed if they weren't part of the project) and the text under proposal partners which suggests adding the applicant again if they are part of the proposal.

Change text to remove the part that causes any doubt that they are part of the proposal.

**Comment by jen-thomas** [comment]
Updated the text as a quick fix.

It would be nice to have a better way of ensuring the applicant is included as a proposal partner if they are going to be part of the project. 
Currently we are assuming that the applicant is going to be part of the project. However it is always possible that someone else would apply on behalf of the project. 

For some of the calls, there are no proposal partners because the proposal should just be for the one person, so this should be considered. 

Possible suggestion: 
- if proposal partners box is ticked when creating a call, then another tick box should appear next to the applicant, asking if they are part of the project. 
- if so, then the role, role description, and competences fields should appear for them to complete
- the text should be changed next to the proposal partners to ensure that the applicant is not then added as a partner

**Comment by cpina** [comment]
I've moved to stage n as we didn't discuss it on stage 2 (and orcid id probably more important)
