### ISSUE TITLE
view of proposal displays organisation as object rather than name

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#145]
When displaying the view of a proposal (for management), the organisation is shown as an object list, rather than the organisation name.

This happens in both the applicant and proposal partners sections.
![Screenshot from 2019-12-03 14-55-08](https://user-images.githubusercontent.com/14336311/70061906-012e7900-15dd-11ea-9461-46d6730c7102.png)
![Screenshot from 2019-12-03 14-55-15](https://user-images.githubusercontent.com/14336311/70061909-01c70f80-15dd-11ea-88f4-334ff47a4375.png)

**Comment by jen-thomas** [comment]
In the section "other sources of funding", the organisation is not displayed at all: 
![Screenshot from 2019-12-03 14-57-17](https://user-images.githubusercontent.com/14336311/70062056-4357ba80-15dd-11ea-856b-91ff30390d6b.png)

**Comment by jen-thomas** [comment]
The same in contact: 
![Screenshot from 2019-12-03 15-14-07](https://user-images.githubusercontent.com/14336311/70063395-96cb0800-15df-11ea-90e4-d9fc35b151d5.png)

**Comment by jen-thomas** [comment]
Organisation name under applicant section now appears correctly. This was fixed. 
Contact organisations also appear correctly.

**Comment by cpina** [comment]
Fixed!
