### ISSUE TITLE
what to do with physical person when editing applicant, overarching person and proposal partner

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#169]
Gender is not saved or retrieved when completing the applicant section of the proposal form

**Comment by jen-thomas** [comment]
currently a physical person is edited / changed if the applicant of a proposal is amended. For now (for the PAF) this is not ideal, but not a huge disaster: it is likely to be one person applying for themselves, so hopefully only typos etc will change, rather than the physical person changing to someone else entirely. 

We need to implement something urgently to ensure people are unique.

**Comment by jen-thomas** [comment]
there is still the problem that an applicant and overarching person can be the same physical person if they have the same first and second names. any changes to either would overwrite the physical person.

**Comment by cpina** [comment]
Physical person problem: ORCID is the way to go

Person Position problems are not fixed by orcid as it identifies a person (not the role of a person at certain time)
