### ISSUE TITLE
Date of PhD format reverts to yyyy-mm when loading editing version of proposal form

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#190]
Date of PhD is a text field because we wanted mm-yyyy format rather than a specific date. Using the date picker widget, this is now possible. 

The required format for the widget is mm-yyyy but for the database is yyyy-mm (which is more standard). 

When a user creates a proposal mm-yyyy is required and allows the form to be saved, but when editing it (before submission), the field loads as yyyy-mm. The user cannot then save the form without changing the format manually back to mm-yyyy.

![Screenshot from 2020-01-14 15-20-18](https://user-images.githubusercontent.com/14336311/72356681-8d09e980-36e1-11ea-8b8f-37d46b4a2a25.png)

**Comment by cpina** [comment]
Fixed

(note that if any data in the database is not correct there might be problems but it should not be possible)
