### ISSUE TITLE
be able to assign reviewers to a proposal

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#213]
"rapporteur in panel" field in diagram of evaluation section. 

Reviewers should be assigned to a proposal so there is history of who has evaluated each proposal.

**Comment by jen-thomas** [comment]
select them from a list of the reviewers that have been assigned to a call?

**Comment by cpina** [comment]
This can be done via admin: model Reviewers in Evaluation app.

This should be done via management but not done yet. Moving to stage-n for the management part.
