### ISSUE TITLE
make evaluation models based on createmodify

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#229]
evaluation models are not currently based on create modify. do this when branches have been merged.

**Comment by cpina** [comment]
This has been done here:
https://github.com/Swiss-Polar-Institute/project-application/commit/96191dea6be04b909903e68084078d662a7b303a
https://github.com/Swiss-Polar-Institute/project-application/commit/73761450a0d994b879d4133810885894f5965690

(modified_on, created_on and history)
