### ISSUE TITLE
add evaluation tab to navigation bar

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#241]
Following conversation on 2020-02-28: 
- evaluation details (completion of results etc) might make more sense under an evaluation section, rather than through call -> proposals or just proposals as evaluation is another stage. 
- this page should essentially show what is now shown under "calls closed" - a list of the closed calls, then navigation to a list of proposals for that call, with all the same navigation buttons

**Comment by cpina** [comment]
Done!
