### ISSUE TITLE
remove excel evaluation button from next to proposal under calls -> open, future, closed calls -> list of proposals

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#242]
Excel evaluation button here could cause confusion. remove it from calls -> open, future closed calls -> list of proposals. It will instead be visible in the same place but under evaluation in the navigation bar.

**Comment by cpina** [comment]
Done!
In "class CallsList(TemplateView):" via "context['evaluation_spreadsheet_button'] = False"
