### ISSUE TITLE
add logic to creation of keywords in proposal form to ensure only short terms are used

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#244]
In a proposal a set of keywords was entered as a string,i.e term1, term2, term3, term4, term5, instead of individually. This causes extra work in ensuring these terms are then added separately to the database and linked correctly to the original proposal. 

Commas should not be allowed in keywords. Consider not allowing other separation characters, but spaces and - should be allowed in case these are part of the term.

**Comment by tbal999** [comment]
Hi there, could take a look.

Whereabouts is the logic for this currently sat within your repository?

**Comment by cpina** [comment]
> Hi there, could take a look.
> 
> Whereabouts is the logic for this currently sat within your repository?

Thanks @tbal999 - very appreciated, but don't worry too much for this one, we have a solution partially done.

We changed the label from "help needed" to "ask SPI" (our organisation) to avoid confusion with external users looking for where to help :-)

This project is only used internally at the moment or by a few users, hopefully in the future we can improve the documentation to help being helped!

If for some reason you are interested in the repo/code let us know and we can send you more information of course (but it's heavily under development).

Cheers,

**Comment by tbal999** [comment]
My motivation is to assist others because

A) I want to improve my open-source portfolio i.e my work experience
B) I enjoy it!

So i'd be happy to help you more if you are OK with that.

**Comment by cpina** [comment]
I understand - I just think that contributing into projects that have more users and have a broader community to give feedback to changes might be more useful. And contributing to some well-known projects always give a good feeling! (and nice to thing that your change is used by millions of people not by a few people).
E.g. Django is very welcoming: https://docs.djangoproject.com/en/dev/internals/contributing/ and has a list of easy to pick tickets: https://code.djangoproject.com/query?status=!closed&easy=1

Another one: this is a very small project that in my opinion needs contributors: https://github.com/elo80ka/django-dynamic-formset/issues (it's very well used but have at the moment lack of maintenance) (it's used by our project as well, they have a list of issues, one I opened it and I didn't even remember: it's a way to contribute in our repo indirectly! We have a bit of a hack to use an older jQuery in the scope of django-synamic-formset).

Anyway, if you want to contribute in the project-application I suggest to install it together with minio (for local object storage), perhaps start writing documentation on the installation as you do it might be good. Make a fork of the repo in your repository and fix things. We are not sizing the tickets at the moment but find something for you (if possible old, sometimes we open tickets and then fix them quick; older ones is more unlikely) and see how it goes!

**Comment by tbal999** [comment]
Thanks cpina, I appreciate your response you've given me some clear direction.

I'll have a look at https://github.com/elo80ka/django-dynamic-formset/issues 
And i'll also fork the repo and look at the older tickets. 
Hopefully one of them will align with my experience level and i'll be able to provide some valid input.

Cheers.

**Comment by jen-thomas** [comment]
commas would be a good separator. Make sure that none of the current keywords have a comma separator though!

**Comment by cpina** [comment]
The GCMD list of keywords have 2 keywords with a comma:
* universal description, discovery and integration (uddi) service
* weeds, noxious plants or invasive plants

So keywords with "," need to be accepted (at least if they come from GCMD list).

A possible solution is:
* In the list of keywords in the Proposal form: filter out keywords with commas created by the users (to not encourage or confuse users)
* A user can still create them (it's hard to have the logic on the Javascript to say in real time that the keyword is not valid, I don't see a way in the Django Autocomplete Light package to do this straight away). So a user can type "a, b, c" and click on "Create"
* On the validation of the form: if a keyword is user created and contains a ",": return an error to the user and say that it's not a valid keyword

So, for the changes:
* autocomplete.py in KeywordsAutocomplete class in the method get_queryset: exclude keywords with a "," if the source is "external user"
* In the clean of ProposalForm in the self.cleaned['keywords']: reject keywords with "," and user created
