### ISSUE TITLE
modify excel evaluation so that criteria come from call evaluation

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#259]
Evaluation criteria vary depending on the call. The excel evaluation has coded values for the criteria. Instead these should come from the call evaluation.

**Comment by jen-thomas** [comment]
- top should display the criteria and what they mean
- next to each proposal the criteria need scoring and remarks boxes

**Comment by jen-thomas** [comment]
Decided for now that this will be done manually by SPI. Added ticket to remove this part of the code so that the evaluation criteria are not now exported to avoid confusion. See #302

**Comment by cpina** [comment]
I think that this was done. To be verified.
