### ISSUE TITLE
on view and edit of call evaluation page, change link "edit evaluation" to "edit call evaluation"

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#262]
not clear that "edit evaluation" goes to edit call evaluation - change text on button

**Comment by jen-thomas** [comment]
Maybe it would be better not to have the "view call evaluation" button on the edit button - it might confuse the user as they are already editing this. 

It would still be useful to have the "edit call evaluation" button when on the call evaluation view page.

**Comment by cpina** [comment]
We have the "view"/"edit" buttons for all the elements (e.g. Call, Template Question, Funding Instrument, Proposal Evaluation... soon Projects probably) so I would say to leave it here for consistency (even though this one is smaller) or remove all of them.

Note that the "View", if we improve things, can be improved for the "Printing" (we would need to hide the comments/attachments) so it might be useful for this. Or we might decide to have a "Print View" if it works better.

**Comment by cpina** [comment]
We've decided to leave the "Edit Call Evaluation" and "View Call Evaluation" so is the same as other pages.
