### ISSUE TITLE
add decision letter file attachment to proposal evaluation

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#264]
attachment of decision letter needs to be attached to a proposal evaluation. 

this also needs a date sent associated with it. 

in the logic of the proposal evaluation, the fact that it has been sent should be included in logic.

**Comment by cpina** [comment]
Done!

**Comment by jen-thomas** [comment]
add date decision letter sent to model and proposal evaluation form
