### ISSUE TITLE
change colour (format?) of text in boxes explaining why eligibility / evaluation buttons do not appear in proposal view

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#273]
The comments describing why a proposal cannot be evaluated / eligibilty edited are very useful. They currently look very similar to comment fields. Changed the colour of the text to a dark grey perhaps? Maybe use italics or something different to highlight the words eligibility and evaluated in the text so that they stand out.

**Comment by cpina** [comment]
Now it's light grey background and italics.
