### ISSUE TITLE
add panel recommendation and board decision columns to list of proposals when navigating from evaluation

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#279]
Panel recommendation and board decision (as tick / cross if possible) would be useful to display next to the eligibility in the list of proposals, but only when navigating from evaluation.

**Comment by cpina** [comment]
Done!
I haven't done tick-boxes because it can be "Reserve", "Fund", "Do not Fund" and we don't have an icon for "Reserve".
