### ISSUE TITLE
unique identifier for people

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#29]
Should people be in a controlled list?
Should there be an optional identifier? ORCID? GASPAR? ResearcherID? Google scholar?

Should the identifier be compulsary?

**Comment by jen-thomas** [comment]
In SPI application drawing, search required by researcher.

**Comment by jen-thomas** [comment]
Person now has a UID so that these can be captured. There is no way of doing this in the form currently.

**Comment by cpina** [comment]
This is all done.
