### ISSUE TITLE
display proposal comments/attachments within view of an individual project

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#290]
Proposal comments and attachemnts will not be copied from proposal to project. Instead they will be displayed in an individual view of a project with or near to the project comments and attachments.

**Comment by cpina** [comment]
The proposal is just a click away ("View Proposal" on the project view) and then the comments/attachments are available.

We've decided to not implement this for now, but will ask SPI if this is wanted or not needed.
