### ISSUE TITLE
improve naming of evaluation summary

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#295]
The evaluation summary page is a little confusing: 
- button on evaluation proposal list
- evaluation summary page: header and section names

-- Suggestions --
Button: 
- keep evaluation summary for when the evaluation has been closed?
- change the name to evaluation validation?

Header: 
- evaluation validation and summary?

Sections: 
- proposal checks -> eligibility validation
- proposal checks -> evaluation validation
- summary - leave as it is

**Comment by cpina** [comment]
This is all done.
