### ISSUE TITLE
add career stage post-doc < 3 years after PhD

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#301]
Add a new stage to the career stage: post-doc < 3 years after Phd. text in the call should also be corrected to ensure that it is explained that SPI are flexible in this regard.

**Comment by jen-thomas** [comment]
Check how this would affect the current database entries. 

Don't like how this would overlap with the post-doc entry that already exists as "post-doc or established scientist".

**Comment by cpina** [comment]
This is done in production and staging. Existing people have been re-assigned to the correct categories.
