### ISSUE TITLE
Check that applicant, overarching project leader and proposal partners have no duplicates

### ISSUE THREAD

**Issue by cpina** [Swiss-Polar-Institute/project-application#303]
When creating a proposal right now the applicant could enter the same physical person (orcid) as applicant and overarching project leader.
It could also enter two proposal partners to be the same person.

On the proposal validation: make sure that the the applicant and overarching project leader are not the same person. Show an error message if this is the case and avoid saving/submitting the proposal

The same in case that the same proposal partner is entered twice.

**Comment by jen-thomas** [comment]
A proposal partner cannot be duplicated currently - this validation already seems to exist.
![Screenshot from 2020-04-15 16-40-31](https://user-images.githubusercontent.com/14336311/79350535-ddd6eb80-7f37-11ea-87bf-7f66cc6ca28a.png)
