### ISSUE TITLE
Proposal partner text in proposal form incorrect when proposal partner form has error

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#326]
In the proposal partner section of the proposal form, the introductory text, "Please enter the details of all partners involved in the {activity}" uses the activity to form the complete sentence so that it makes sense for the different types of calls. The activity is highlighted in blue in the example screenshot below: 
![proposal_partner_text_error](https://user-images.githubusercontent.com/14336311/79356127-dc5cf180-7f3e-11ea-98f4-c2d2996f6778.png)

When an error occurs in the proposal partners form, this sentence no longer uses the activity, leaving an incomplete sentence: 
![proposal_partner_duplicate_error](https://user-images.githubusercontent.com/14336311/79356252-ff87a100-7f3e-11ea-999e-fb33c3d16da0.png)
Note that the {activity} is missing.

**Comment by cpina** [comment]
This was fixed some weeks ago. We can re-test just in case.
