### ISSUE TITLE
evaluation summary: show total number of proposals submitted

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#327]
The evaluation summary text shows a number of figures about the number of proposals that have been received, eligible and funded or not. 
![evaluation_summary_text](https://user-images.githubusercontent.com/14336311/79365680-3c599500-7f4b-11ea-8bd7-719e409868c9.png)

For a management user, the "number of proposals received" could be a bit confusing and interpreted as the number that were submitted. Currently the number presented shows the total number of proposals that were created, but this includes both the draft and submitted proposals.

The number of submissions would be a number that could be better interpreted by a management user.

**Comment by cpina** [comment]
Fixed in grant-management branch, will be merge into master soon
