### ISSUE TITLE
displays projects funded on call evaluation closed page

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#328]
When the call evaluation is closed, a confirmation page is displayed showing the number of projects that have subsequently been created. 

![call_evaluation_closed](https://user-images.githubusercontent.com/14336311/79366527-a45cab00-7f4c-11ea-80ef-1fad09e940a1.png)

Further confirmation to the management user could be given by listing the projects created (i.e. PI name and project title) with a direct link to the project view.

**Comment by cpina** [comment]
Done in 4b62151aa269a19dc3357d1a07480d4560bf88db (grant-management branch)
