### ISSUE TITLE
Add ORCID logo and link next to names in project view

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#329]
Displaying the ORCID logo and linking directly to the ORCID page is done on the proposal view and could be useful for a management user to be able to quickly find the PI online on ORCID.

**Comment by jen-thomas** [comment]
Names where they occur throughout the rest of the project views could also have the ORCID link: 
- grant agreement signed by
- overarching project leader
- proposal partners

**Comment by cpina** [comment]
This is done in the grant_management branch
