### ISSUE TITLE
Validate project start and end dates in grant management project information

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#330]
A management user is able to modify the project start and end dates so validation would ensure that mistakes cannot be made. Editing of the dates is required because project timings can vary depending on many factors.

Validate: 
- end date > start date
- start date > call end date

**Comment by cpina** [comment]
Done in d56a6a31334e71ddd9f81aca1f0fa722e4b049a8 branch grant-management
