### ISSUE TITLE
Financial invoice due date not saved if no other dates are entered

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#331]
Due date is the only mandatory field of a financial invoice. The other dates will be added from time to time so it is not possible to have an invoice with mandatory fields for all of these other dates. 

If an invoice is created by entering a due date, the due date is not saved and displayed in the table of invoices in the grant management view of a project.

**Comment by cpina** [comment]
Done in grant-management branch
