### ISSUE TITLE
Validate the financial invoice form

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#332]
Dates related to financial invoices should be validated to prevent errors and ensure that different measures of using these dates are correct, such as the timeline on the latest news, email notifications of certain events, etc. 

Validate: 
- due date (mandatory)
- due date > project start date
- date received > project start date
- date sent for payment >= date received
- date paid >= date sent for payment
- due date < project end date
- amount <= project budget allocated
- file attached if date received is completed
- if date sent for payment: date received mandatory
- if date paid: date sent for payment mandatory

**Comment by cpina** [comment]
Implemented (pending further verification and unit tests, which will be done in a separate ticket) in grant-management
