### ISSUE TITLE
Grant agreement: can have multiple signatories

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#341]
A grant agreement can have multiple signatories on the side of the applicant which can therefore in turn also have multiple signing dates.

This means that not all signatories would necessarily be listed in the proposal (and therefore would not be listed in the database). 

A signatory  on the side of SPI is not needed.

**Comment by cpina** [comment]
This is now implemented. Example URL: http://127.0.0.1:8000/logged/grant-management/grant-agreement/8/update/
