### ISSUE TITLE
Link invoices to payment installments

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#346]
Payment installments are defined at the time of the grant agreement (and they depend on the funding instrument and project). They are normally paid as a percentage, but again this varies.

Every invoice will be linked to an installment. Normally the amount of the invoice should be the same  as the installment, but it could occasionally be less. Exceptionally there could be more than one invoice for an installment.

**Comment by cpina** [comment]
Done in c19d6d37d1141989ec166c244afd3856a632e4ce and previous commits
