### ISSUE TITLE
Project display edit

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#347]
A management user needs to be able to edit details of a project, such as the title (in case of typos), keywords (in case of typos or additions) and other fields. Currently there is no way to edit these details either  in the project detail view or through the grant management view. 

We should consider how these pages would be used by a management user and where they would most likely end up.

**Comment by cpina** [comment]
This is done - From Grant management (http://localhost:8000/logged/grant-management/project/14/) there is "View Project" and from there there is "Edit Project": http://localhost:8000/logged/grant-management/project/14/update/
