### ISSUE TITLE
Unable to edit a financial report

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#352]
## Problem
Once financial reports have been completed, to avoid mistakes, they are uneditable. All fields in the financial report form are greyed out once the fields have been completed and the form saved.

In order to make changes to any of the fields, the "approval date" needs to be deleted by the user, the form saved and the financial reports page reopened. Whilst this does not ultimately stop a user changing all of the information, it is a barrier to making accidental mistakes.

Currently, deleting the "approval date" and saving the form, does not make the other fields editable because the form validation fails on save: if the "approved by" is completed then the "approval date" is also required. 
![image](https://user-images.githubusercontent.com/14336311/82919390-40c79380-9f76-11ea-9043-6d4472dca585.png)
(note that in the image the approved by field has been covered to avoid displaying a name)

## Steps to reproduce: 
- enter a financial report - complete all fields
- click save
- navigate back to the financial reports page
- delete the "approved date" field
- click save

**Comment by cpina** [comment]
This is done - now "Approved by" and "Approval date" are always editable so both can be left blank to unlock the Report changing.
