### ISSUE TITLE
duplicated information about project start and end dates in headers

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#367]
On the grant management page, we noticed that the project start and end dates are repeated in the two headers. 

![image](https://user-images.githubusercontent.com/14336311/87167261-fd7a7780-c2cc-11ea-8fd6-07569d18d2b0.png)

It might make more sense to have the dates in the second section and retain the applicant / grantee information in the first.

**Comment by cpina** [comment]
This has been amended.
