### ISSUE TITLE
improve format of project information in header

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#368]
On the project view page, the project information header is long and it is a bit confusing seeing the project end date on the right-hand side (in other places it is directly below the project start date). 

![image](https://user-images.githubusercontent.com/14336311/87167642-94473400-c2cd-11ea-8208-a6e3d5e615d7.png)

It could be improved by putting the keywords and geo information in a column on the right hand side, which would also save space.

**Comment by cpina** [comment]
Improved in different commits recently.
