### ISSUE TITLE
Autocomplete boxes do not resize with narrow-width browser resolutions

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#371]
When screen or browser is narrower, some autocomplete boxes do not resize, overlapping with other fields.

**Example**: deliverables, milestones

![image](https://user-images.githubusercontent.com/14336311/88276993-41637880-cce0-11ea-97bd-70e140d0ccaa.png)

**Example**: deliverables, scientific reports, approval

![image](https://user-images.githubusercontent.com/14336311/88277065-60620a80-cce0-11ea-8af9-7dba8839ca4b.png)

**Comment by cpina** [comment]
Done! (https://github.com/Swiss-Polar-Institute/project-application/commit/cc8dfcf2af0cb5340b63c0f83279276db25d148f)
