### ISSUE TITLE
Add grantee / applicant address

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#372]
The address of a grantee or applicant is used for communication, such as sending the decision letter or grant agreement. Currently this is not part of the application form and therefore can be very tricky to find. 

The applicant's address (that should be used for correspondance) could be included in the application form so it can be used to send the initial decision letter. 

Adding it as part of the person position for the applicant would mean that it is possible for it to appear with the proposal and project, but could also change (as it is not with the physical person) as the person moves to different institutions. 

Having the address as a text box is an option. Structuring the full address is tricky to account for variation in all possible countries. Validation for all parts of an address is tricky as well because of variation between countries. It might be useful to have separate fields for the postcode, city and country. 

A country list could come from the ISO list of [countries](https://www.iso.org/iso-3166-country-codes.html) (to avoid duplications).

**Comment by cpina** [comment]
Fixed!
