### ISSUE TITLE
Pre-populate short name and long name of call from funding instrument and finance year when creating call

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#375]
The long and short names of the call are used in various places so it is useful if they are in the same format, but it can be confusing for a user to make sure that they are done in the same way each time. 

To avoid problems, it would be helpful to pre-populate these in the call creation / edit form so that there are less / no mistakes. 

Long name format: funding instrument name financial year, eg. SPI Technogrants 2019
Short name format: financial key code financial year eg. TEG 2019

**Comment by cpina** [comment]
Done! When adding a call it makes the long/short name disabled and it's changed via Javascript based on the funding instrument and the finance year
