### ISSUE TITLE
reformat presentation of call questions on call edit

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#377]
Consolidate the view of a question listed on the call edit to make it easier to check and reorder if necessary: 

![image](https://user-images.githubusercontent.com/14336311/88785908-19698e80-d192-11ea-99e0-9c332ee718a7.png)

Suggestions: 
- question text: smaller box and on the first row
- answer type, max length and answer required on same line
- change "order" field to "question number"? Put this on first row as the first field, or above the question text line?

**Comment by cpina** [comment]
Done! (required is in a different line because it seems to look nicer)
