### ISSUE TITLE
remove button not available to remove proposal partner in proposal form

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#385]
When the form was in a strange state (not able to save because of duplicate proposal partner: see issue #384 ): 

![image](https://user-images.githubusercontent.com/14336311/88805107-09ac7300-d1af-11ea-86e9-fb03e06bba51.png)

and another proposal partner was added using the "add another" button, the "remove" button is not then available to get rid of a partner: 

![image](https://user-images.githubusercontent.com/14336311/88805312-46786a00-d1af-11ea-8d96-108f406f7e3d.png)

No "remove" option is available until the submission has been saved (and failed again): 

![image](https://user-images.githubusercontent.com/14336311/88805550-948d6d80-d1af-11ea-8182-bbe1fe3297d3.png)

**Comment by cpina** [comment]
The state that the form showed "duplicated partners" but they were not displayed has been fixed (#384)

I've updated jquery.formset.js and it fixed some issues with the "remove" button and I think that this is one of the issues for what I can see.

I'm closing it but we can re-open if needed.
