### ISSUE TITLE
add validation for applicant / partner roles

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#391]
In the calls where a proposal partner can be added, the applicant must add their and the partners' roles. These are chosen from a pre-defined list. 

Validation is needed to ensure that 
- only one person (applicant or one of the partners) is entered as a PI, 
- there must be at least one PI or two co-PIs (some people might decide to represent the partners as such)

**Comment by cpina** [comment]
Fixed!
