### ISSUE TITLE
Cannot delete head of research unit from proposal form

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#393]
Head of research unit cannot currently be removed from the proposal form.

Steps to reproduce:
- Delete the ORCID
- The names are removed
- Try to remove the academic title (not possible - need to select one from list)

![image](https://user-images.githubusercontent.com/14336311/90316613-941d0280-df23-11ea-954f-ab9ffdab3914.png)

- Save draft of form
- Open link to view / edit form
- Head of research unit has not been deleted

![image](https://user-images.githubusercontent.com/14336311/90316603-86677d00-df23-11ea-8cae-1eefe13f54f4.png)

**Comment by cpina** [comment]
Fixed!
