### ISSUE TITLE
Should ORCID (or other unique identifier) be used to distinguish people?

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#4]

**Comment by jen-thomas** [comment]
Possible options: 
International Standard Name Identifier ISNI: http://www.isni.org/
Open Ownership: https://www.openownership.org/
ORCID: https://orcid.org/

**Comment by jen-thomas** [comment]
ORCID
- used for PLOS authors (required)
- used for Zenodo publications (optional)

**Comment by cpina** [comment]
After discussing it with the team we decided to use ORCID.

This is now implemented.
