### ISSUE TITLE
Reporting: add table of overall submissions

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#411]
Need number of proposals submitted per grant, per year (also this could include the number that are funded eventually).

eg. 
| Grant | 2018 submitted | 2018 funded | 2019 submitted | 2019 funded | 
|---| --- | --- |  --- | --- |
| PAF | # | # | # | # |

**Comment by cpina** [comment]
Done! (in two tables, but changes in the Reporting section might happen soon when SPI is going to use it more)
