### ISSUE TITLE
should it be possible to export a submitted proposal to an excel spreadsheet?

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#55]
In SPI application diagram, there is the requirement to export a proposal to an excel spreadsheet. 

The reasons for this should be determined, so that it is decided whether this is important or not and if so, how it should be formatted for the best use.

**Comment by cpina** [comment]
I'll close this one: we have now the "Evaluation sheet" with some of this information and I'll open a new one for the proposal+attachments as zip. They superseed this one.
