### ISSUE TITLE
should location be removed from the proposal model?

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#63]
(specific) location is a charfield in proposal that was used as a way of capturing in more detail the geographical coverage of the project. 

If we can incorporate a better list of geographical area, perhaps we should consider removing this field. It is not currently possible to enter anything for this in the form.

**Comment by jen-thomas** [comment]
Add to form as free text field (coversation with Laurence and Basil, Nov 2019 EPFL)

**Comment by cpina** [comment]
Done: https://github.com/Swiss-Polar-Institute/project-application/commit/889504142aa65ae24e4937b92a47f1770117b1f2
