### ISSUE TITLE
agreement to privacy policy

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#72]
In the initial proposal form, the user should be able to accept or decline agreement to the data policy. There should be a boolean option for this in the model. 

In the form they can accept or decline. 

If they accept, the form can be submitted. Still need to know what happens if they decline.

**Comment by jen-thomas** [comment]
Added to model

**Comment by jen-thomas** [comment]
QUESTION - what should happen to the proposal if they do not accept?

**Comment by jen-thomas** [comment]
If do not accept, then proposal cannot be submitted (conversation with Laurence and Basil, Nov EPFL)

**Comment by cpina** [comment]
This is what's happening (checkbox is a required field and needs to be clicked in order to proceed)
