### ISSUE TITLE
Unknown column 'project_core_budgetcategory.order' in 'field list'

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#82]
![Screenshot from 2019-11-05 16-02-40](https://user-images.githubusercontent.com/14336311/68224020-c9d0aa80-ffe5-11e9-8e91-434647b141af.png)

Clicking on "view" on GLACE proposal from this page:http://127.0.0.1:8000/management/proposals - see error in attached screenshot

**Comment by jen-thomas** [comment]
Same for edit: http://127.0.0.1:8000/management/proposal/b902278e-b154-4c5c-a38e-84815424280e/update

**Comment by cpina** [comment]
This column should have been added by this migration:
https://github.com/Swiss-Polar-Institute/project-application/blob/master/ProjectApplication/project_core/migrations/0075_budgetcategory_order.py

Let's check on the computer...

**Comment by cpina** [comment]
could you send please the output of:
python3 manage.py showmigrations

Mine, without the error, includes:
 [X] 0075_budgetcategory_order

I'd like to see if you have this migration applied or not

**Comment by jen-thomas** [comment]
Solved :)
