### ISSUE TITLE
Add list of organisation(s) to the contact detail page

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#83]
Contact detail pages (contact-detail.tmpl) would be nice with the list of organisations to whcih they belong in addition to the group. 

This could be for the edit page and view page.

**Comment by cpina** [comment]
Done!
I'm not sure if the visualization is the best one (or if it could be better). Right now is a list of organisations separated by commas. I'll check if we had something else in some other view, for now this is closed...
