### ISSUE TITLE
ensure that all proposals have a partner that is a principal investigator if proposal partners are asked for in call

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#88]
Proposal partners can be added to a call as a question. 

Currently there is no requirement for a proposal to have a principal investigator. 

Should there have to be a PI, or at least two Co-I's?

**Comment by cpina** [comment]
This was implemented in the Proposal Partners. On the other hand: the Proposal Partners section is not currently used (it might come back again at some point though). I'll close for now since the original request is done.
