### ISSUE TITLE
cannot select data policy and newsletter tickboxes when creating a contact

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#89]
it is not possible to select the tickboxes when creating a contact

**Comment by cpina** [comment]
This was done on purpose to avoid that we (SPI) clicks the tickboxes by mistake.

It has the problem that cannot untick them if the user wants them revoked.

For now we will leave this way and think more (e.g. maybe it should only revoke in case that people contacts SPI?).
