### ISSUE TITLE
check deadline date format of call in different browser configurations

### ISSUE THREAD

**Issue by jen-thomas** [Swiss-Polar-Institute/project-application#99]
When testing the call creation, the date format appeared as mm/dd/yyyy hh:mm am/pm where the am/pm was not obvious. It looks as though the user has to use an up or down arrow on the keypad to get this to work. Otherwise the call cannot be created....

Check if there is a way to overcome this problem so that it is not a problem for different browser configurations. 

Otherwise add some help text.

**Comment by cpina** [comment]
(I've updated the original message changing TZ to am/pm, it's what it was)

Now (pending deployment to production, already on staging): we are using XDSoftDateTimePickerWidget and the described problem doesn't apply there.
Initially it was using the native widgets (Chrome, Firefox, Safari, IE) but they behaved different and were confusing
